name: Release Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: |
          mvn clean package
          cd target
          mv Gameboard-1.x.jar GameboardVorlage.jar
                
      -   name: Release
          uses: softprops/action-gh-release@v2
          with:
              body_path: GB_CHANGELOG.MD
              files: |
                  GB_CHANGELOG.MD
                  target/GameboardVorlage.jar
              token: ${{ secrets.GH_TOK }}